# Generated by Django 4.0 on 2022-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_to_user_alter_message_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=256)),
            ],
        ),
    ]
