# Generated by Django 4.0 on 2022-04-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_id'),
        ('message', '0003_messageclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclient',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
