# Generated by Django 4.0 on 2022-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messageclient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('seen', 'seen'), ('removed', 'removed')], default='sent', max_length=20),
        ),
    ]
