# Generated by Django 4.0 on 2022-04-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageClient',
        ),
    ]
