# Generated by Django 4.0 on 2022-04-25 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_delete_messageclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_messaged',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
