# Generated by Django 4.0 on 2022-04-26 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0007_contact_last_messaged_contact_new_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='new_message',
        ),
        migrations.AddField(
            model_name='contact',
            name='new_message_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_message_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
