# Generated by Django 4.0 on 2022-03-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('number', models.CharField(max_length=30)),
                ('add_number', models.CharField(max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=30)),
                ('location', models.JSONField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Reviewed', 'Reviewed'), ('Expired', 'Expired')], default='Open', max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('number', models.CharField(max_length=30)),
                ('add_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('location', models.JSONField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donor_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.donorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
            ],
        ),
    ]
