# Generated by Django 4.0 on 2022-02-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_rename_request_bloodrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='location_name',
        ),
    ]
