# Generated by Django 4.0 on 2022-04-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_alter_bloodrequest_status_favoriteuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
