# Generated by Django 4.0 on 2022-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_alter_bloodrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
