# Generated by Django 4.0 on 2022-04-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_delete_userreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteUser',
        ),
    ]
