# Generated by Django 4.0 on 2022-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_bloodrequest_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='description',
            field=models.TextField(default='test desc', max_length=500),
            preserve_default=False,
        ),
    ]
