# Generated by Django 4.0 on 2022-02-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodrequest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='slug',
        ),
    ]
