# Generated by Django 4.0 on 2022-04-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_remove_notification_data_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdata',
            name='users',
        ),
    ]
