# Generated by Django 4.0 on 2022-02-25 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_donorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='blood_request',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest'),
            preserve_default=False,
        ),
    ]
