# Generated by Django 4.0 on 2022-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_remove_notificationdata_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdata',
            name='type',
            field=models.CharField(choices=[('NEW_BLOOD_REQUEST', 'NEW_BLOOD_REQUEST'), ('DONOR_REQUEST_GOT', 'DONOR_REQUEST_GOT'), ('BLOOD_REQUEST_UPDATED', 'BLOOD_REQUEST_UPDATED'), ('BLOOD_REQUEST_DELETED', 'BLOOD_REQUEST_DELETED'), ('DONOR_REQUEST_ACCEPTED', 'DONOR_REQUEST_ACCEPTED'), ('DONOR_REQUEST_NOT_ACCEPTED', 'DONOR_REQUEST_NOT_ACCEPTED'), ('DONOR_REQUEST_REJECTED', 'DONOR_REQUEST_REJECTED'), ('DONOR_REQUEST_CANCELED', 'DONOR_REQUEST_CANCELED'), ('DONOR_REQUEST_RESTORED', 'DONOR_REQUEST_RESTORED'), ('DONOR_REQUEST_DELETED', 'DONOR_REQUEST_DELETED'), ('DONOR_REQUEST_UPDATED', 'DONOR_REQUEST_UPDATED'), ('DONOR_REQUEST_REVIEWED', 'DONOR_REQUEST_REVIEWED'), ('BLOOD_REQUEST_REVIEWED', 'BLOOD_REQUEST_REVIEWED')], max_length=300),
        ),
    ]
