# Generated by Django 4.0 on 2022-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_donorrequest_blood_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
