# Generated by Django 4.0 on 2022-03-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_donorrequest_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donorrequest',
            old_name='accepted',
            new_name='isAccepted',
        ),
    ]
