# Generated by Django 4.0 on 2022-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='open', max_length=30),
        ),
    ]
