# Generated by Django 4.0 on 2022-03-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorrequest',
            name='isAccepted',
        ),
        migrations.AddField(
            model_name='donorrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='open', max_length=30),
        ),
    ]
