# Generated by Django 4.0 on 2022-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0014_remove_donorrequest_isaccepted_donorrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
