# Generated by Django 4.0 on 2022-03-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_alter_donorrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Reviewed', 'Reviewed'), ('Expired', 'Expired')], default='open', max_length=30),
        ),
        migrations.CreateModel(
            name='DonorRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('donor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donorrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.FloatField()),
                ('description', models.TextField(max_length=500)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest')),
            ],
        ),
    ]
