# Generated by Django 4.0 on 2022-03-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_alter_bloodrequest_status_donorrequestreview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequestreview',
            old_name='review',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='donorrequestreview',
            old_name='review',
            new_name='rating',
        ),
    ]
