# Generated by Django 4.0 on 2022-03-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_rename_review_bloodrequestreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestreview',
            name='blood_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.bloodrequest'),
        ),
        migrations.AlterField(
            model_name='donorrequestreview',
            name='donor_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood.donorrequest'),
        ),
    ]
