# Generated by Django 4.0 on 2022-02-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_imgs')),
                ('name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=25)),
                ('add_number', models.CharField(max_length=25)),
                ('location', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
