# Generated by Django 4.0 on 2022-02-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
