# Generated by Django 4.0 on 2022-02-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
