# Generated by Django 4.0 on 2022-02-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='jjj@ggg.com', max_length=100),
            preserve_default=False,
        ),
    ]
